id = "gruber-flavors"
name = "Gruber Flavors"
version = "0.8.0"
schema_version = 1
authors = ["blaqat <blaqat.ag@gmail.com>"]
description = "15 flavors of a theme for recreational programmers."
repository = "https://github.com/biaqat/gruber-theme-zed"
