id = "gruber-theme"
name = "Gruber Theme"
version = "0.6.0"
schema_version = 1
authors = ["blaqat <blaqat.ag@gmail.com>"]
description = "A theme for recreational programmers."
repository = "https://github.com/biaqat/gruber-theme-zed"
